//
// Generated file, do not edit! Created by nedtool 5.2 from inet/raptorqimplementation/application/base/ApplicationPacketRq.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET_APPLICATIONPACKETRQ_M_H
#define __INET_APPLICATIONPACKETRQ_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

/**
 * Class generated from <tt>inet/raptorqimplementation/application/base/ApplicationPacketRq.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // Generic application packet
 * //
 * packet ApplicationPacketRq
 * {
 *     long sequenceNumber;
 * }
 * </pre>
 */
class INET_API ApplicationPacketRq : public ::omnetpp::cPacket
{
  protected:
    long sequenceNumber;

  private:
    void copy(const ApplicationPacketRq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ApplicationPacketRq&);

  public:
    ApplicationPacketRq(const char *name=nullptr, short kind=0);
    ApplicationPacketRq(const ApplicationPacketRq& other);
    virtual ~ApplicationPacketRq();
    ApplicationPacketRq& operator=(const ApplicationPacketRq& other);
    virtual ApplicationPacketRq *dup() const override {return new ApplicationPacketRq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual long getSequenceNumber() const;
    virtual void setSequenceNumber(long sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ApplicationPacketRq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ApplicationPacketRq& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_APPLICATIONPACKETRQ_M_H

